ivpusic/react-native-image-crop-picker

- android/src/main/java/com/reactnative/picker/RealPathUtil.java
Android gallery on KitKat returns different uri
```
content://media/external/images/media/3951
content://com.android.providers.media.documents/document/image:3951
```
> Use better function to get real path

- android/src/main/java/com/reactnative/picker/PickerModule.java
- ios/ImageCropPicker.m
Add the base64 image data, in the response returned
> Add base64 data in result 

- ios/ImageCropPicker.m
Instead, cross-dissolve from image picker to cropper. User should feel continuous experience in taking/choosing picture to cropping.
To not introduce a flash between presented view controllers, the easiest way to do this is to present the image cropper on top of the image picker, and then dismiss the whole stack.
> Remove slide-down/slide-up animation between choosing image and cropping

- ios/ImageCropPicker.m
I introduced this bug, but here's the fix
> Fixed bug where user couldn't cancel out of cropping (ios)

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
- example/app.js
- ios/ImageCropPicker.m
set the setCircleDimmedLayer to "cropperCircleOverlay" option on react-native.
> add support to uCrop setCircleDimmedLayer()

- ios/Compression.m
Reverts ivpusic/react-native-image-crop-picker#199
> Revert "support ios 8"

- ios/Compression.m
Reverts ivpusic/react-native-image-crop-picker#200
> Revert "Revert "support ios 8""

- ios/ImageCropPicker.h
After trying the instructions multiple times, I wasn't able to get anywhere until I tried the following:
http://stackoverflow.com/a/41664041/752815
This helped as well:
https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.eyvdfp97f
> Fix for unknown imports

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
- ios/ImageCropPicker.h
- ios/ImageCropPicker.m
- ios/imageCropPicker.xcodeproj/project.pbxproj
Hey @ivpusic,
I added a method openCropper in order to directly crop an image by specifying the path of the file.
Tested on Android & IOS, let me know if it looks good to you :)
Thanks
> openCropper method added

- android/src/main/java/com/reactnative/ivpusic/imagepicker/RealPathUtil.java
https://github.com/ivpusic/react-native-image-crop-picker/issues/259
> Fix resolving external storage paths

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
```
ImagePicker.openCropper({
...
enableRotationGesture: true
hideBottomControls: true
})
```
> (android) Add 'hideBottomControls' & 'enableRotationGesture' -options

- index.d.ts
The typescript definition file lost openCropper and clean function. And now I add it.
> Add missing function for typescript definition file

- ios/ImageCropPicker.m
> fix orientation (iOS)

- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
related issue: https://github.com/ivpusic/react-native-image-crop-picker/issues/353
> fixed a bug when using openCamera with [multiple: true]

- README.md
- ios/ImageCropPicker.h
- ios/ImageCropPicker.m
Reference on #384 
This PR adds two new response property: one is `localIdentifier`, the other is `filename`
> returned localIdentifier and filename in response

- ios/ImageCropPicker.m
Dictionary was being created with nil values. Added nil check and initialize with empty string instead
> Fix for crash on ios when selecting image

- README.md
- ios/ImageCropPicker.m
reference #395 
- added a new option: `minFiles`
- added a new response property: `sourceURL`
- updated README
> added minFiles option, and a new response called sourceURL

- ios/ImageCropPicker.m
> bug fixed - check if the source URL is empty or nil

- android/build.gradle
Fix save file path issue of this package in this new version 2.1.0
> Use new version of id.zelory compressor package

- ios/ImageCropPicker.h
Fixes https://github.com/ivpusic/react-native-image-crop-picker/issues/436
> Change import priority of React/RCTBridgeModule.h

- index.d.ts
Added additional interface which grabs all functions and also added a constant which will be used as a default export
> TypeScript 2.6.0 default export fix

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
- ios/Compression.m
- ios/ImageCropPicker.m
Note: creationDate is not available on Android due to limitations of the `File` class
> Add creation and modification date to response

- ios/ImageCropPicker.m
What do you guys think about this?
As reported in https://github.com/ivpusic/react-native-image-crop-picker/issues/252 and https://github.com/ivpusic/react-native-image-crop-picker/issues/449, file sizes end up around 3x larger when not specifying compression and resizing. Plus I need the ability to retrieve photos without any modifications.
This change skips the image compressor when the requested compression is 1 (or not specified) and max width/height are equal/larger than the original dimensions (or not specified). iOS only.
Feedback appreciated.
> Skip image compression when not desired (iOS)

- ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
- ios/QBImagePicker/QBImagePicker/fr.lproj/QBImagePicker.strings
- ios/imageCropPicker.xcodeproj/project.pbxproj
Adds a French strings file for iOS 🇫🇷🇨🇦
> French localization for iOS

- README.md
- ios/ImageCropPicker.m
Changes the "Move and Scale" header to the `cropperToolbarTitle` prop.
Solves https://github.com/ivpusic/react-native-image-crop-picker/issues/370
> custom label for iOS

- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
As uCrop (on which this lib relies for Android) supports this feature I thought it would be very nice feature to have this.
> Added option to set free style crop for android.

- android/src/main/java/com/reactnative/ivpusic/imagepicker/Compression.java
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
As discussed with @fubar, these changes are the android equivalent of those that were made for iOS.
**I haven't yet had time to test these changes.**
> Added android equivalent code for skipping image compression.

- android/src/main/java/com/reactnative/ivpusic/imagepicker/Compression.java
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
Reverts ivpusic/react-native-image-crop-picker#749
> Revert "Added android equivalent code for skipping image compression."

- example/app.js
The example project had a small typo, this is fixed by this PR. I'm currently using the actual implementation of the feature and it works as expected (apart from the example).
This was signaled in a comment in #791
> Fix typo on example project for forceJpg

- android/src/main/java/com/reactnative/ivpusic/imagepicker/RealPathUtil.java
Fixes https://github.com/ivpusic/react-native-image-crop-picker/issues/670
> Fall back to writing to file if _data column does not exist

- README.md
Add optional configuration details about default ios text button for the camera and the gallery
> Update README.md to add ios configuration for default Camera/Gallery button localization

- .npmignore
> Remove images from npm bundle

- ios/src/ImageCropPicker.m
> fix ios camera with cropping not reject on cancel cropping

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
expose showCropFrame option for android
Resolve [#614](https://github.com/ivpusic/react-native-image-crop-picker/issues/614)
> (android) add showCropFrame option

- ios/src/ImageCropPicker.m
https://github.com/ivpusic/react-native-image-crop-picker/issues/994
Fix suggested in the thread above.
> iOS Bug Fix - Cancel at cropper cause error 

- RNImageCropPicker.podspec
https://github.com/facebook/react-native/commit/2321b3fd7f666ce30f5dad4cd2673ddf22972056#diff-7538dfd5a1053e07f15cfe72274360caR10
> Update pod dependency to support rn 0.60

- README.md
Not all Android devices handle useFrontCamera
https://github.com/ivpusic/react-native-image-crop-picker/issues/1058#issuecomment-514286714
> Clarify README.md (#1058)

- README.md
related issue:
https://github.com/ivpusic/react-native-image-crop-picker/issues/1112
> fixed `jitpack.io` url in readme.md

- ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m
- ios/QBImagePicker/QBImagePicker/QBImagePicker.storyboard
- ios/src/ImageCropPicker.m
Added correct colors for iOS 13 DarkMode in picker
> Added iOS 13 DarkMode for picker

- ios/src/ImageCropPicker.m
This kind of warnings also presents in output console if Main Thread Checker is active.
> Fix xCode warnings about main thread execution

- README.md
- android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
- example/app.js
- example/ios/Podfile.lock
- index.d.ts
- Add toolbar widget color for title and buttons (Fix #1315).
- Update README and example project.
- Update library version in `Podfile.lock` to the latest version `0.32.0`.
> Add Cropper Toolbar title color

- README.md
- index.d.ts
Several simple type improvements.
> Add types for smart albums, compressed video presets, and picker errors

- android/build.gradle
> Fix android crash by updating to newest uCrop

- README.md
Fixed a typo in the documentation.
> Docs typo fix

- ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
- ios/QBImagePicker/QBImagePicker/ko.lproj/QBImagePicker.strings
* Added korean loc file for iOS
* Fixes french loc issue
> Korean localization for iOS

- ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
- ios/QBImagePicker/QBImagePicker/it.lproj/QBImagePicker.strings
- ios/QBImagePicker/QBImagePicker/pt.lproj/QBImagePicker.strings
- ios/QBImagePicker/QBImagePicker/zh-Hant.lproj/QBImagePicker.strings
Italian(it), Portuguese(pt) and Traditional Chinese(zh-Hant)
> Added Italian, Portuguese, and Traditional Chinese language

- ios/src/ImageCropPicker.m
Fix the video not loading/downloading from iCloud as suggested by @anhkieet in #1415.
> Fix video not loading from iCloud

- ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
- ios/QBImagePicker/QBImagePicker/tr.lproj/QBImagePicker.strings
> turkish language strings added

- README.md
- index.d.ts
- ios/src/ImageCropPicker.m
https://github.com/ivpusic/react-native-image-crop-picker/issues/1651
@ivpusic Could you please review?
>  #1651 iOS cropper rotation function disable

- ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
- ios/QBImagePicker/QBImagePicker/da.lproj/QBImagePicker.strings
- ios/imageCropPicker.xcodeproj/project.pbxproj
> Add Danish Language

- README.md
minor spelling mistake fix.. nothing crazy 😅 
changed "greather" to "greater"
> fix spelling error in readme.md

- index.d.ts
> Property 'Latitude' does not exist on type 'object' in exif

- README.md
word fix::: changed "localizate" to "localize"
> docs: readme typo fix

- ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m
We noticed that one of the views for selecting images was not accessible and would like to make it accessible. This was based on user feedback.
> Make list items accessible
