android/src/main/java/com/reactnative/picker/PickerModule.java

I added the camera support of this package, which is base on the implementation of react-native-image-picker. I added another function call openCamera which basically allows user to launch the camera once the permission is granted. In the mean time the user also can continue to crop or rotate the image after finished taking photo from camera. I used the same options as openPicker.

added camera support for react-native-image-crop-picker

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

should check if (mPickerPromise == null) first in croppingResult  just like other result calling:imagePickerResult and cameraPickerResult. Because when app's mainActivity resumed and called onActivityResult can you get the mPickerPromise.

add if (mPickerPromise == null) to croppingResult 

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

- Default colors for the cropper are less aggressive (not UCrop's orange)
- If cropperTintColor is passed in, this overrides status bar, toolbard, and widget UX items.
Default colors if no `cropperTintColor` passed in:

Allow user to specify brand color for cropper

---

README.md
ios/ImageCropPicker.m

For easily setting an avatar picture, it is nice to be able to choose the front facing camera as the default.
This is trivial on iOS, on Android it's [a little more complicated](http://stackoverflow.com/questions/2779002/how-to-open-front-camera-on-android-platform) so implemented just for iOS for now.

Allow choice of default camera (front vs. back) on iOS

---

ios/ImageCropPicker.m

Allows ImagePicker.openCamera().then() handler to perform Alert.alert.
Test case:
```objc
import {Alert} from 'react-native';
ImagePicker.openCamera({
compressImageMaxWidth: 1024,
compressImageMaxHeight: 1024,
compressImageQuality: 0.7,
})
.then((image) => {
Alert.alert('Picture taken')
});
```
In existing codebase
--
- The Alert is not displayed.  Repeat with a Chrome breakpoint on the Alert line - wait a few seconds, then continue = Alert displayed. Demonstrates this is a timing issue
With this PR
----
- the alert is displayed every time, regardless of whether there's a breakpoint or not.
The same logic has been applied to each .reject() too.
Tested via Xcode 8.2.1, React Native 0.41.2 on iPhone 6 running iOS 10.2

iOS: Wait for viewController to dismiss before resolving or rejecting

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Possibility to hide the default 3x3 -grid on the image during cropping.
```
ImagePicker.openCropper({
...
showCropGuidelines: false
});
```

Add possibility to hide crop guidelines

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

According to [official docs example](https://developer.android.com/reference/android/os/Environment.html#getExternalStoragePublicDirectory(java.lang.String)), you need to make sure that the external storage directory you want to manipulate (`Environment.DIRECTORY_PICTURES`, in this case) exists.
When running the previous code in Android 4.4 (KitKat), the method `PickerModule#createImageFile()`  throws an IOException, because there was no existing directory when calling `File#createTempFile()`. This behavior was documented in the issue #283.
So, I've just called `path.mkdirs()` to create the directory, inside an `if` statement that checks if the folder doesn't exist (which is not necessary, but make things more clear, though).

#283 Create DIRECTORY_PICTURES if it doesn't exist

---

ios/imageCropPicker.xcodeproj/project.pbxproj

Referencing #287, the previous header search paths reference the React Native version from the example project, as opposed to that of the actual source project that the lib is included from. It was causing errors if there was inconsistency between the example and the actual project.

Update HEADER_SEARCH_PATHS to be more compatible

---

ios/ImageCropPicker.h
package.json
react-native-image-crop-picker.podspec

FYI @ivpusic. I'll leave the documentation updates to you.
Fixes #307 
Now you simply add this to your `Podfile` with no reference to any other dependency and run your app:
```
pod 'react-native-image-crop-picker', path: 'node_modules/react-native-image-crop-picker'
``` 
Note: I put my `Podfile` in the app root (not `[root]/ios`) so the path would change if you used default pattern of sticking it in `[root]/ios`.
```
pod 'react-native-image-crop-picker', path: '../node_modules/react-native-image-crop-picker'
```

Add podspec

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Now we can specify **Toolbar**, **Statusbar** and **active-widget** color. If not specified it defaults to default colors.

Add more color options in RN Image crop picker

---

ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
ios/RSKImageCropper/RSKImageCropper.xcodeproj/project.pbxproj

This PR removes your TeamID out of the XCode-Projectfiles. When the TeamID is included, XCode 
does it not allow to create an Archive unless the current developer is member of your team.
The issue that will be fixed here is:
> No "iOS Development" signing certificate matching team ID "5WFBC66J2G" with a private key was found.
More information about this issue you can find here: https://github.com/ruslanskorb/RSKImageCropper/issues/164
It does not break any compatibility.

Removed TeamID from XCode-project-file.

---

ios/ImageCropPicker.h

When I try to compile my app in release I got a compilation error with this line:
```
#import "RSKImageCropper/RSKImageCropper.h"
```
I try everything, clean the cache, remove pod dependencies and reinstall, unlink an link again, but nothing works, the only solution I found is to change the import to this:
```
#import <RSKImageCropper/RSKImageCropper.h>
```
Doesn't seems to be a big difference, but it's now working for me

Fix RSKImageCropper not found

---

ios/Compression.m

-[origin] if ([maxWidth integerValue] == 0 || [maxHeight integerValue] == 0) {
-When pick a width< height image and only set "compressImageMaxWidth",will cause  {0,0}size image.
-Now i fix it.

[iOS] Fix  a bug that cause a {0,0} size image

---

ios/ImageCropPicker.m

I have getting crashes with selecting >30 images at once some times on iOS. I noticed that the less free memory you have, the more chance to get the crash you have.

Fix for adding files more than 30 at once for iOS

---

ios/ImageCropPicker.m

Dictionary was being initialized with nil values which causes crash in Obj-C. I've put a ternary in that will send empty string values for the possible nil values

Fix crash when taking photo from camera on ios

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerPackage.java

createJSModules was removedin React Native 0.47.0 and results in the attached Build Error.
removing `@Override` fixes build (didn't remove function because I don't know if it should be kept for downard compatability?)
```
node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerPackage.java:18: error: method does not override or implement a method from a supertype
@Override
^
Note: /node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED
```

Fix Compilation Error in React Native 0.47.0

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/Compression.java

For fix bug replace original image

Create another file for compressed picture with different name

---

README.md

Added additional example to the code snippets provided, showing how to select videos with the ImagePicker. 
Also documented the behaviour whereby having the prop 'cropping' set to true results in no videos being shown on Android. I have stated that this issue is known to have happened, rather than stating that it happens all the time, due to the relative poor test coverage across the broad spectrum of Android devices available.

Added video docs

---

index.d.ts

Try to mute the warning of "[ts] Module react-native-image-corp-picker has no default export"
After careful consideration, I have not increased the typescript example in the readme file, because the code of typescript and javascript are almost the same.
Really appreciate all your kind help.

Update index.d.ts to mute the error message

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

I needed to change the toolbar title but didn't know any other way so I thought about adding this functionality. Currently, as my knowledge is limited to java, this is currently only available for Android.
Example usage:
```
ImagePicker.openCropper({
path: 'image.png',
width: 800,
height: 800,
cropperToolbarTitle: 'Please, crop your photo',
})
```
Will result in this:
If no title is provided, the default one from the library will be used.

[Android] Add option to set the cropper toolbar title

---

ios/imageCropPicker.xcodeproj/project.pbxproj

Hey!
Warning
```
[07:47:52]: no rule to process file '...../react-native-image-crop-picker/ios/ImageCropPicker.h' of type sourcecode.c.h for architecture arm64
[07:47:53]: ▸ no rule to process file '....../ios/UIImage-Resize/UIImage+Resize.h' of type sourcecode.c.h for architecture arm64
```
Due `*.m` files includes `*.h` files, we dont needed to compile `*.h` files
Expected:
Thank

[Fix] iOS: Remove *.h files from Compile Sources

---

README.md
android/build.gradle
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
index.d.ts
ios/ImageCropPicker.m

Hey, @ivpusic! Please review.
- Add `cropRect` response object
- `cropRect` is an Object typeof `CropRect`
- Use latest uCrop version `2.2.1` with the [ability](https://github.com/Yalantis/uCrop/issues/285) to get cropped image offset coordinates
```javascript
...
cropRect: {
x: 268,
y: 0,
width: 393,
height: 393
}
...
```

Return cropped image rectangle

---

ios/imageCropPicker.xcodeproj/project.pbxproj

ios build occasionally fails.
```
=== BUILD TARGET imageCropPicker OF PROJECT imageCropPicker WITH CONFIGURATION Release ===
~~~
#import <RSKImageCropper/RSKImageCropper.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
~~~
** ARCHIVE FAILED **
```
- react-native 0.47.1
- react-native-image-crop-picker 0.19.0
- RSKImageCropper 2.0.0
- QBImagePickerController 3.4.0
- Xcode 9.1
I looked at the log of xcodebuild.
The build order is different each time.
It seems to be an error if imageCropPicker is build before RSKImageCropper.
```
=== BUILD TARGET RSKImageCropper OF PROJECT RSKImageCropper WITH CONFIGURATION Release ===
~~~
=== BUILD TARGET imageCropPicker OF PROJECT imageCropPicker WITH CONFIGURATION Release ===
~~~
** ARCHIVE SUCCEEDED **
```
```
=== BUILD TARGET imageCropPicker OF …
```

[Fix] ios 'RSKImageCropper/RSKImageCropper.h' file not found

---

README.md
ios/ImageCropPicker.m

Until now the user could only choose to show smart albums from the default set of 5 albums ('UserLibrary', 'PhotoStream', 'Panoramas', 'Bursts', 'Videos').
I fixed it and added support for all types of smartAlbums, as listed here:
https://developer.apple.com/documentation/photos/phassetcollectionsubtype/phassetcollectionsubtypesmartalbumgeneric
In the future we can add support for the other types of album subtypes, including the wildcard "any" (listed here: https://developer.apple.com/documentation/photos/phassetcollectionsubtype)

Add support for all types of smart albums (selfies, time lapses, etc.)

---

ios/ImageCropPicker.m

There was an extra colon in the response property for creationDate. There is no more ✅

fix typo in creationDate property in response

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Found a better solution to the issue which is described in [#581](https://github.com/ivpusic/react-native-image-crop-picker/pull/581). Hope this one is better than the previous attempt.

Added an flag to the gallery intent to prevent two instances of it

---

README.md
ios/ImageCropPicker.m

Disk i/o is slow. When I use the `includeBase64` option to retrieve file contents directly, I have no use for a temporary file written to disk.
This PR adds a `writeTempFile` option (default true) that I can use to skip writing of those temporary files.
iOS only.

Add option for writing temporary file

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

UCrop uses colors from overriden xml values but if we always set the colors from the setters it overrides the values taken from the xml. I've added a flag to disable the cropper color setters in order to use the android xml colors file like this:
```xml
<color tools:override="true" name="ucrop_color_toolbar">#color</color>
<color tools:override="true" name="ucrop_color_toolbar_widget">#color</color>
<color tools:override="true" name="ucrop_color_widget_background">#color</color>
<color tools:override="true" name="ucrop_color_statusbar">#color</color>
<color tools:override="true" name="ucrop_color_widget">#color</color>
<color tools:override="true" name="ucrop_color_widget_active">#color</color>
<color tools:override="true" name="ucrop_color_widget_text">#color</color>
```

Flag to disable color setters fro Ucrop

---

index.d.ts

Several Android-only options were missing from the TypeScript `Options` interface, causing compiler warnings in client codebases when used.

Update TypeScript typings with some Android-only options

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
index.d.ts
ios/src/ImageCropPicker.m

Rebased the branch from https://github.com/ivpusic/react-native-image-crop-picker/pull/618 - work by Eslam Sabry (@smsmdida), just following up on the comment from that PR.

Add chooseText and cancelText properties: rebased

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/RealPathUtil.java

Thanks for creating awesome project.
Recently I've used this library for small project and everything worked great except on Android 4.2 
( API < 19 ). When I click confirm of cropping, it crashes right away. So I looked up into source code and found out that `import android.provider.DocumentsContract` library is available since Android Kitkat which is API 19 or above. 
This fixes #730

[fix/android] Android API version under 19 crash fix

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/Compression.java
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

The updated PR to the old one. The following test have been performed:
GIF (300x 200) and DNG (2000 x 1000) file with the following settings:
```compressQuality: 0.8 ``` -> Converted both to `jpeg`
```compressQuality: 0.8, compressMaxWidth: 100, compressMaxHeight: 100``` -> Converted both to `jpeg`
```compressMaxWidth: 100, compressMaxHeight: 100``` + individually -> Converted both to `jpeg`
```compressQuality: 1``` -> Only converted `DNG` to `jpeg`
```compressQuality: 1, compressMaxWidth: 500, compressMaxHeight: 500``` -> Only converted `DNG` to `jpeg`
```No settings set``` -> Only converted `DNG` to `jpeg`

Added android equivalent code for skipping image compression.

---

README.md
index.d.ts
ios/src/ImageCropPicker.m

I have encountered a case where specific images were not able to fit in the crop, setting the flag `avoidEmptySpaceAroundImage` to false fixes this issue. Currently this library has this value hard-coded. This PR allows this parameter to be configurable, defaulting to true as this is the current behaviour.

Added option to configure avoidEmptySpaceAroundImage

---

README.md
example/app.js
index.d.ts
ios/src/ImageCropPicker.m

Adds a `forceJPG` flag to force the lib to convert target images. This will be mostly helpful when images contain Live Images but only Still images are wanted.
How it works:
Calling `UIImageJPEGRepresentation` will force any images to return their JPG equivalent, even if they're Live Photos.

Adds forceJpg flag to convert live photos

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

In order to use front camera, add following to `app\src\main\AndroidManifest.xml` in your project.
```
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" android:required="false" />
<uses-feature android:name="android.hardware.camera.front" android:required="false" />
```

Add front camera support for android

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

I did some searching and there are different flags for different phones, in my case previous flag for Android was not working with a Google Pixel phone, Im adding 2 new flags tu support more android phones

Added missing flags to support front camera on some android phones

---

README.md

I verified that this step ("drop the ios/ImageCropPickerSDK folder to your xcode project") is not required using Xcode 9.4.1, iOS 11.4 and React Native 0.55.4 when doing a manual install.
Adding the ImageCropPickerSDK folder would also trigger the "CFBundleIdentifier Collision" error on TestFlight as reported in issue #61.

Remove problematic step from manual post-install steps for iOS

---

README.md

If `image.data` is already base64 encoded string, why do we need this wrapper?
The proposed change worked for me on ios and android.

Simplify `includeBase64`

---

index.d.ts

In typescript project, we can not access directly some properties.
`filename`, `creationDate`, and `modificationDate` are useful properties for user.

Add some types for Image interface

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

The inputstream not close when base64 image file:
> com.reactnative.ivpusic.imagepicker.PickerModule#getBase64StringFromFile
This will case app exist by the exception:
```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1803)
at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
at java.io.FileInputStream.finalize(FileInputStream.java:487)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
at java.lang.Daemons$Daemon.run(Daemons.java:103)
at …
```

[Android] autoclose inputstream when base64 image file

---

README.md
index.d.ts
ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m
ios/QBImagePicker/QBImagePicker/QBImagePickerController.h
ios/src/ImageCropPicker.m

Adds support for ordering the photos by creation date (ascending or descending) on iOS. By default, it'll keep the behavior that's currently on the library, which is that sort order is unspecified.
Related issues:
#953

Adds a sortOrder flag to sort by creation date on iOS

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

The `openCropper` function does not check `WRITE_EXTERNAL_STORAGE` permission like `openPicker` or `openCamera` do, so in this PR I checking it (and ask for grant if needed) before startCropping method called. It's is a fix of [#957](https://github.com/ivpusic/react-native-image-crop-picker/issues/957) issue

check permission before startCropping. Fix of #957

---

ios/src/ImageCropPicker.h
ios/src/ImageCropPicker.m

I'm using RN 0.61
The IOS project of react-native-image-crop-picker is importing the deprecated RCTImageLoader.h file. React-RCTImage pod doesn't export this header anymore.
With a simple fix, inspired by [this post](https://github.com/react-native-community/react-native-svg/issues/1141#issuecomment-540940897) the lib is working again.

Fix deprecated RCTImageLoader.h import

---

ios/src/ImageCropPicker.m

UI-related code should run in main thread, as exception says:
`Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'threading violation: expected the main thread'`
Fixes #1139

Fix crash after video recording in ios13 & xcode11

---

RNImageCropPicker.podspec

I faced an issue today where CocoaPods could not properly install this library because the tag version was incorrect.  This should fix that!
Why?
* Ruby uses `"` quotes when interpolation is required.  Using `'` will mean `v#{version}` 
is used directly rather than providing the version number.
Changes:
1. User Ruby string interpolation when setting the tag version for the source.

CocoaPods - Properly Interpolate Tag Version

---

README.md

Clarify that **avoidEmptySpaceAroundImage** option is (**ios only**)

Update README.md (Clarify avoidEmptySpaceAroundImage option)

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
ios/src/ImageCropPicker.m

PR for possibility to get duration of the picked video.
related issue - https://github.com/ivpusic/react-native-image-crop-picker/issues/181
This PR will be helpful for video validation, especially when you need to set a limit for uploaded video.
**Implemented on both (Android | IOS)**
In **"Response Object"** you will get duration property in milliseconds.
Tested on Android and IOS.
Duration will be available from local file(path) or cloud(any link as well)
Updated READMY file => **Response Object section**
The PR doesn't have additional dependencies or global changes.

Duration of the picked video (in milliseconds)

---

ios/src/ImageCropPicker.m

Related to : #1290 
If we use `cropperCircleOverlay` in iOS, it's different from Android, it creates a circular cropped image on a white background. 
* **iOS**
* **Android**
I think it's good to have the same result regardless of platforms. An image with a white background makes it difficult to use in a service by using `borderRadius`.
Please review positively.

[iOS] Fixed to be cropped the same as Android

---

ios/src/ImageCropPicker.m

Good morning! This is a really cool package, but I faced a slight setback when trying to integrate it into [our application](https://github.com/artsy/eigen). The problem lies with some swizzling we do with our application delegate (using [JSDecoupledAppDelegate](https://github.com/JaviSoto/JSDecoupledAppDelegate)). It's not a common practice, especially among React Native applications, but the result is that `[[[UIApplication sharedApplication] delegate] window]` returns `nil`. This causes the call to [`presentViewController:animated:completion:`](https://github.com/ivpusic/react-native-image-crop-picker/blob/a0c7a8f4b591c864c8025d0eb2360b8270311301/ios/src/ImageCropPicker.m#L360) to silently fail. In our app, we typically use `[[UIApplication sharedApplication] keyWindow]` instead, …

Fixes possibly nil window lookup

---

index.d.ts

This PR covers a few type-related improvements.
- Separate `Image` and `Video` types.
- Make return types for `openPicker` and `openCamera` conditional. Now the return types change based on the input props. For example, the return type will only be an array if the `multiple` prop is present.
- Add documentation to every property for improved IntelliSense.
I've used this in production for several weeks but another set of eyes would be awesome.

Conditional return types, and documentation for every property

---

index.d.ts

When I used openCropper method, TypeScript says 'path' is not available field for parameter object type.
The parameter object type of openCropper method is ImageOptions. There is not path field on ImageOptions Type.

Add path field to ImageOptions on typescript

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Now `react-native-image-crop-picker` allow to choose any `image/*` file for cropping. But related to https://github.com/Yalantis/uCrop/issues/166#issuecomment-245606245 only `libjpeg` and `libpng` under the hood libUCrop. So I think will be useful to filter image files only ready for cropping
ref https://github.com/ivpusic/react-native-image-crop-picker/issues/1367#issuecomment-686576364

[android] filter possible image types for cropping

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

@ivpusic Sorry, my bad. In PR #1421 I didn't think about those who don't need cropping, who need the picker only. Now images filtered if cropping only

[android] filter image types if cropping only

---

index.d.ts

Hey!
I noticed that showCropFrame is missing from TS typing

Add showCropFrame to Typescript typing

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
index.d.ts
ios/src/ImageCropPicker.m

Hi!
First of all, thanks for the lib and your work on it 💪 
This PR brings consistency in permission-related error codes between iOS & android 
=> breaking change
Fixes #770 
PS: tested on iOS + android (except ios camera flow, due to simulator limitation)

fix: Make sure to return precise + platform-consistent permission error code

---

ios/src/ImageCropPicker.m

HEIC format (introduced in iOS 11) needs to be handled for determining MIME type

Add heic format for determining MIME type

---

index.js

We declared that named exports are exist in [`index.d.ts`](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/index.d.ts#L471-L475), but they are not exist in `index.js`.
This PR exports these named exports in `index.js` that we can really use named import and get benefits with tree-shaking like this: 
```ts
import { openCamera } from 'react-native-image-crop-picker
openCamera()
```

fix(export): export named functions to match definitions

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Sometimes the length of the video cannot be retrieved.

Sometimes I get an error on Android.

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/Compression.java
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

- Refined target dimension algorithm to ensure both height and width are less than their corresponding max values
- Avoid using separate bitmap instances to allocate less memory
- Use exif orientation instead of bitmap rotation to avoid calling extra `Bitmap.createBitmap`

Fix image compression OOM exception

---

ios/QBImagePicker/QBImagePicker/QBAlbumsViewController.m
ios/QBImagePicker/QBImagePicker/de.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/en.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/es.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/fr.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/it.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/ja.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/ko.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/pl.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/pt.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/ro.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/ru.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/sv.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/tr.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/uk.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/zh-Hans.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/zh-Hant.lproj/QBImagePicker.strings

I've added this to the top of the album list, to help users understand they have limited the access to their album and a quick way to change their selected photos/videos or application permissions.

Adding messenger inspired iOS 14 limited permission help

---

ios/QBImagePicker/QBImagePicker/QBAlbumsViewController.m
ios/QBImagePicker/QBImagePicker/ja.lproj/QBImagePicker.strings
ios/QBImagePicker/QBImagePicker/zh-Hans.lproj/QBImagePicker.strings

Fixes https://github.com/ivpusic/react-native-image-crop-picker/issues/1678
And adding missing translations.

Adding support for dark mode in limited permission help

---

ios/src/ImageCropPicker.m

fix [#1658 ](https://github.com/ivpusic/react-native-image-crop-picker/issues/1658)

fix view blinks on ios15 if enable cropping flag

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
android/src/main/java/com/reactnative/ivpusic/imagepicker/RealPathUtil.java

"Invalid image selected" error throwing when image path is not readable because of scoped storage.
Copy file to external cache directory when the file is not reachable to resolve this issue.

Fix android "Invalid image selected" issue

---

ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
ios/QBImagePicker/QBImagePicker/vi.lproj/QBImagePicker.strings
ios/imageCropPicker.xcodeproj/project.pbxproj

Add Vietnamese language

---

RNImageCropPicker.podspec

Summary
We have noticed several crashes due to a RuntimeException for our App on iOS devices. The StackTrace given in the Xcode console is as follows.
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHPhotoLibrary presentLimitedLibraryPickerFromViewController:]: unrecognized selector sent to instance 0x7fd348a7b9b0'
*** First throw call stack:
(
0   CoreFoundation                      0x00007ff800427378 __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007ff80004dbaf objc_exception_throw + 48
2   CoreFoundation                      0x00007ff800436588 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   CoreFoundation                      0x00007ff80042b83d ___forwarding___ + 1431
4   CoreFoundation …
```

fix(1742):runtime exception in PHPhotoLibrary

---

ios/QBImagePicker/QBImagePicker.xcodeproj/project.pbxproj
ios/QBImagePicker/QBImagePicker/fi.lproj/QBImagePicker.strings
ios/imageCropPicker.xcodeproj/project.pbxproj

Add Finish Language

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

* Fix for openPicker not working when app targets Android 13 on Android 13 device
Note: Developers must also add the READ_MEDIA_IMAGES images permission in their manifest files.
Essential Links to understand the PR change
Android 13 documentation on the new granular permissions : https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions
Bug raised on Google which confirms we need READ_MEDIA_IMAGES for Android 13 and above instead of WRITE_EXTERNAL_STORAGE - https://issuetracker.google.com/issues/237634019
Issue created against this fix on github - https://github.com/ivpusic/react-native-image-crop-picker/issues/1849

Fix for openPicker not working when app targets Android 13

---

README.md
index.d.ts
ios/src/ImageCropPicker.m

This PR adds a way to customize iOS cropper toolbar using custom (HEX only) colors for the toolbar buttons (`Choose` and `Cancel`).
If I would pass custom colors to `openCropper` or `openPicker` it would apply provided colors
`openCropper` example:
```ts
async function launchCropper() {
const imageUri: string = await SomeImageUtils.openPicker();
return await ImageCropper.openCropper({
path: imageUri,
mediaType: 'photo',
cropperChooseColor: '#00E78A',
cropperCancelColor: '#FFFFFF',
});
}
```
or `openPicker` example:
```ts
async function launchPicker() {
return await ImageCropper.openPicker({
cropperChooseColor: '#00E78A',
cropperCancelColor: '#FFFFFF',
});
}
```
And if I would not pass any custom colors it would fallback to default values
`openCropper` example:
```ts
async function …
```

[iOS only] Feat: Add the way to customize iOS cropper toolbar

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Revert PR https://github.com/ivpusic/react-native-image-crop-picker/pull/1852
The permission **READ_MEDIA_IMAGES** is not required to open the image picker on Android 13.
> **Note:** If your app only needs to access images, photos, and videos, consider using the [photo picker](https://developer.android.com/about/versions/13/features/photopicker) instead of declaring the **READ_MEDIA_IMAGES** and **READ_MEDIA_VIDEO** permissions.
Source: https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions

[revert] Fix for openPicker not working when app targets Android 13

---

README.md

In order to use v0.39.0, user must change SDK version to 33. If not, it throws error at https://github.com/ivpusic/react-native-image-crop-picker/blob/75955f0ef3d3bef13b246523646934cc69f0a604/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L406

Update README about Android SDK version

---

ios/QBImagePicker/QBImagePicker/QBAssetsViewController.m

See commit messages for details.
Fixes #1251

Fix handling of deleted photos on iOS

---

ios/src/Compression.m

Fixes #2054
[`UIGraphicsBeginImageContext()`](https://developer.apple.com/documentation/uikit/1623922-uigraphicsbeginimagecontext) is deprecated in iOS 17 and when the width or height is 0, it throws an exception.
The solution is to replace it with [`UIGraphicsImageRenderer`](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer?language=objc).
See [blog post](https://remarkablemark.org/blog/2024/05/04/how-to-fix-ios-ui-graphics-image-error/).

fix(ios): replace `UIGraphicsBeginImageContext` in Compression.m

---

RNImageCropPicker.podspec
ios/PrivacyInfo.xcprivacy
ios/imageCropPicker.xcodeproj/project.pbxproj

Add Privacy Manifest for [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393), .creationDate & .modificationDate

Add Privacy manifest

---

ios/QBImagePicker/QBImagePicker/nl.lproj/QBImagePicker.strings

Added an extra translation inside QBImagePicker for Dutch (nl).

add Dutch (nl) as a translation for iOS

---

RNImageCropPicker.podspec

Please approve this PR and release a new version as it includes the crucial fix for the latest version 2.7.4 of TOCropViewController dependency which eliminates the PrivacyInfo.plist file error in the latest RN version >= 0.74.

URGENT: Updated RNImageCropPicker.podspec

---

ios/src/ImageCropPicker.h

Incomplete #import statements cause the compiler to crash when checking for dependencies
Remove this redundant `#import`.

Fixes an issue that would cause the compiler to crash in Xcode 16 beta1

---

android/build.gradle
android/src/main/AndroidManifest.xml

Test Plan:
https://github.com/react-native-community/discussions-and-proposals/issues/671
React Native 0.73 will depend on Android Gradle Plugin (AGP) 8.x. This will require all the libraries to specify a namespace in their build.gradle file. We added a compatibility layer for libraries that haven't specified a namespace, but please consider updating your libraries nonetheless.

feat(android):RN-0.73 and AGP 8.0 Compatibility

---

android/src/main/AndroidManifest.xml
ios/src/Compression.m

Fixed: [2100](https://github.com/ivpusic/react-native-image-crop-picker/issues/2100)
Fixed: [2104](https://github.com/ivpusic/react-native-image-crop-picker/issues/2104)
Fixed: [2105](https://github.com/ivpusic/react-native-image-crop-picker/issues/2105)

fix: [iOS] Image is being resized up instead of down & Error "User did not grant library permission." in Android 10

---

README.md
android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java
index.d.ts

Resolves: https://github.com/ivpusic/react-native-image-crop-picker/issues/1078

Enhancement:: Add: Filename in response object for Android

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

We're observing width/height being incorrectly reported by the library on Android with portrait photos. This fix, similar to the logic [here](https://github.com/expo/expo/blob/24f5f68e82f527b631c3a19c8a70f06a5ce62968/packages/expo-image-picker/android/src/main/java/expo/modules/imagepicker/exporters/DimensionsExporter.kt#L11-L34), is to swap the reported width/height if the EXIF tag specifies a rotated orientation.
This aligns with the library's behavior on iOS where the width/height are swapped for photos with rotated EXIF.
Verify that portrait photos (I was using Samsung Galaxy A12) report flipped dimensions, just like the iOS version does.

Fix openCamera reported dimensions for portrait photos on Android

---

ios/src/ImageCropPicker.m

This is a PR to fix the issue where the order of selected items is not preserved on iOS.
<table>
<tr>
<th>AS-IS</th>
<th>TO-BE</th>
</tr>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/7b977f9a-8878-42d7-bc12-411504d1f382" width=300 />
</td>
<td>
<video src="https://github.com/user-attachments/assets/260c770f-3fe8-493a-8c75-4a3ebc069204" width=300 />
</td>
</tr>
</table>

[BugFix - ios] Keep selection order 

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Fix the issure in Android where the photo picker does not support a maxFiles selection limit.

Fix the issure in Android where the photo picker does not support a maxFiles selection limit.

---

android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Fix the error in the "setConfiguration" function when retrieving "maxFiles" from "options". If the "maxFiles" keyword is missing, assign a default value of 5 to align with the documentation.

If the "maxFiles" keyword is missing, assign a default value of 5 to align with the documentation.

---

android/build.gradle

In version `0.42.0`, `react-native-image-crop-picker` used `com.github.yalantis:ucrop:2.2.6-native`. However, subsequent versions (including the current `0.51.0`) switched to the non-native variant without documented reasoning (or I didn't find anything like that while browsing the repository).
This change introduced a regression where cropping fails when part of the crop area extends beyond the image boundaries, resulting in:
- Error: "Cannot find image data" 
- Underlying UCrop error: "y must be >= 0"
- Complete failure to crop the image
Set to the native variant (`2.2.11-native`) which handles boundary conditions gracefully, matching the behavior from version `0.42`.
```gradle
- implementation 'com.github.yalantis:ucrop:2.2.11'
+ implementation 'com.github.yalantis:ucrop:2.2.11-native' …
```

Android: Update UCrop dependency to native variant (2.2.11-native)
